### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#104]
## What do you need?

More useful search.

Users tell us a snippet with the search term highlighted in context would be valuable.

## Good example

Any Google search.

![screen shot 2017-03-10 at 2 53 07 pm](https://cloud.githubusercontent.com/assets/13774080/23781420/49a2636c-05a1-11e7-8f47-06336b009646.png)

**Comment by gazanson** [comment]
Now being tracked in Trello
