### ISSUE TITLE
Retain search query in search box

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#113]
## What do you need?

To remind the user which search term they used on the search results page.

![screen shot 2017-03-24 at 5 07 55 pm](https://cloud.githubusercontent.com/assets/13774080/24282581/8dce6626-10b4-11e7-9588-21c9209b41cf.png)

One way to do this would be to retain the search query in the box ala 18F.

![screen shot 2017-03-24 at 5 08 06 pm](https://cloud.githubusercontent.com/assets/13774080/24282585/911eadf4-10b4-11e7-9f6b-56e5ac94beba.png)

## Which entry/section is this related to?

Any search result

**Comment by gazanson** [comment]
Now being tracked in Trello
