### ISSUE TITLE
Make sure single quotation is not entered as an apostrophe (accessibility issues)

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#117]
Copying over @NoniH's issue:

When single quotation marks are entered as an apostrophe, Jaws screen reader doesn't recognise it as quotation.

Suggestion: Add advice about how to create a single quotation mark rather than using apostrophes.

Open quote = option-]
Close quote = option-shift-]

**Comment by joolswood** [comment]
Talk to Noni about drafting

**Comment by joolswood** [comment]
Check if this is still problem with Jaws, and check other screenreaders.

**Comment by joolswood** [comment]
Cassandra to lead on this.

**Comment by joolswood** [comment]
https://waffle.io/govau/content-guide/cards/59e53efe2a53eb017ae6655f

**Comment by gazanson** [comment]
Now being tracked in Trello
