### ISSUE TITLE
Review First Australians guidance

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#119]
## What do you need?

Some people in UR sessions couldn't quickly tell our recommendations on terms to use in the First Australians content. Just want to review this and maybe add a `Do use` list as well as a `Don't use` list.

## Which entry/section is this related to?

http://content-guide.apps.staging.digital.gov.au/accessibility-inclusivity/#aboriginal-and-torres-strait-islander-peoples

**Comment by gazanson** [comment]
Request was for "a *Do use* list as well as a *Don't use* list". Advice about what to use is actually embedded in the sub-topics below.  Rather than 'force' a 'Do use' list on this topic, it might be enough to flagwave this in a standalone sentence "The topics below provide examples of preferred usage."

**Comment by gazanson** [comment]
For discussion. See "quoted matter" below for possible insertion.

--------------------------
https://guides.service.gov.au/content-guide/accessibility-inclusivity/#aboriginal-and-torres-strait-islander-peoples

Aboriginal and Torres Strait Islander peoples

The terms ‘First Australians’ and ‘Aboriginal and Torres Strait Islander peoples’ (note the plural) include distinct and diverse cultural groups. These terms do not represent a homogenous group.

[Below derives from Flinders University guidance - http://www.ipswich.qld.gov.au/__data/assets/pdf_file/0008/10043/appropriate_indigenous_terminoloy.pdf]

"When referring to these peoples, you should use terms that stress their humanity.  

Use:

Indigenous Australian people/s
Aboriginal people/s
Aboriginal person
Torres Strait Islander people/s
Torres Strait Islander person "

Don’t use:

Aboriginals, Aborigine — these words are associated with colonisation and assimilation and are distressing to many people
ATSI — never use the acronym ATSI as this is considered disrespectful
Aboriginal and/or Torres Strait Islander
Aboriginal and Torres Strait Islander Australians

**Comment by joolswood** [comment]
Strongly suggest omitting `When referring to these peoples, you should use terms that stress their humanity.`

**Comment by gazanson** [comment]
SUGGESTED COPY:

The terms ‘First Australians’ and ‘Aboriginal and Torres Strait Islander peoples’ (note the plural) include distinct and diverse cultural groups. These terms do not represent a homogenous group.

When referring to these peoples, you should use their language group — for example  ‘Ngunnawal people’. If you don’t know this, use:

> Indigenous Australian people/s
> Aboriginal people/s
> Aboriginal person
> Torres Strait Islander people/s
> Torres Strait Islander person 

Don’t use:

> Aboriginals, Aborigine — these words are associated with colonisation and assimilation and are distressing to many people
> ATSI — never use the acronym ATSI as this is considered disrespectful
> Aboriginal and/or Torres Strait Islander
> Aboriginal and Torres Strait Islander Australians

**Comment by gazanson** [comment]
@libbyv @joolswood to review. Content Crit 17/10 - "Take the change out for consultation after Libby and Jools review once more. Put to group to say it's restructured and ask 'is it better?'"

**Comment by joolswood** [comment]
I've got a Trello ticket to work on this in is sprint @gazanson

**Comment by gazanson** [comment]
Now being tracked in Trello
