### ISSUE TITLE
How to write date of birth

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#126]
Suggestion from Jane Childs: "noticed there's no explicit recommendation around how to write a DOB. In Identity we have followed the UK style and use:
24 3 1989
Is that something to include in the date section? Might be more of a UI Kit issue? .."

Could be split between Design and Content guides.

**Comment by joolswood** [comment]
Sarah C and I talked about just adapting the UK one https://www.gov.uk/service-manual/design/dates - just adding another example.

**Comment by gazhands** [comment]
Please refer to here peeps https://trello.com/c/figP8Uhu

**Comment by joolswood** [comment]
Yes, there's a couple of other issues in other repos now on same topic - we need to bring this back together. First pattern for the new guidance maybe @gazhands ?

**Comment by gazhands** [comment]
Yes :)

**Comment by joolswood** [comment]
This needs to be discussed with Guides / UI-Kit team about where the doco would go.

**Comment by gazanson** [comment]
Now being tracked in Trello
