### ISSUE TITLE
Fix hardcoded baseurl in search results

### ISSUE THREAD

**Issue by gordcorp** [govau/content-guide#133]
The search results weren't including the baseurl in each result, so as a quick hack I added a prefix "/content-guide". https://github.com/govau/content-guide/commit/53533b5d4739cf77972e307e8fa6e4b8e20182fa

This will have broken the search results everywhere else e.g. staging.

**Comment by bjgordon** [comment]
Using `{{ baseurl }}`  is supposed to work, but it didn't for me... https://github.com/slashdotdash/jekyll-lunr-js-search/issues/41

**Comment by gazanson** [comment]
Now being tracked in Trello
