### ISSUE TITLE
Add advice around non-breaking spaces

### ISSUE THREAD

**Issue by gordcorp** [govau/content-guide#134]
## What do you need?

Not sure if this is within the scope of this guide, feel free to close if not. Can I request some guidance around the use of non-breaking spaces and [word joiners](http://www.fileformat.info/info/unicode/char/2060/index.htm)?

**Comment by gazanson** [comment]
Not sure this IS within the scope of the guide. If it is, we could maybe rework the Style Manual description: "Non breaking spaces are used between parts of an expression that should not be split over a line break -- for example, telephone numbers and in expressions such as Mrs EB Bloch and 3.5 metres." Not sure we should include the more technical 'word joiner' though (used for 'zero-width no-break spaces'); maybe a UI-Kit entry?

**Comment by joolswood** [comment]
Tracking this in Trello. Thanks @gordcorp We'll figure this out and let you know.
