### ISSUE TITLE
Full stops after hyperlinks

### ISSUE THREAD

**Issue by libbyv** [govau/content-guide#144]
Add guidance around not using full stops after hyperlinks, if agreed

**Comment by joolswood** [comment]
No full stops after email addresses that end sentences --- and this doesn't apply to regular links (you should use link text not URL).

**Comment by joolswood** [comment]
Hi @gazanson can you keep the ticket open (ie. `in progress` until there's content changed in the Guide. We can link the change directly to this task.

**Comment by gazanson** [comment]
Ah okay. That would apply to #161 as well, which Libby did online in
yesterday's meeting!  Gary

**Comment by joolswood** [comment]
Tracking in Trello.
