### ISSUE TITLE
SA feedback - email

### ISSUE THREAD

**Issue by libbyv** [govau/content-guide#150]
We have analysed your Gov.AU content in the past week and we’re pleased to see that DECD aligns in all major areas. I have included some more detailed feedback below about areas that we suggest could be expanded upon in your content guide. This would help meet the needs of content writers across government.
 
As a government department we constantly come up against ‘over capitalising’ of communications content, and so our default rule is ‘if in doubt, use lower case’. We have specific ‘rules’ about letter case, which we label as 2 tiers. We need a lot more detail about these types of rules in order to have consistent and clear rules within our department. This level of detail would be very helpful in Gov.au. You can see our explanations of these rules on pages 10 to 14 of our writing style guide.
 
Titles including Minister – we have followed Gov.UK and the Style Guide for Authors Editors and Printers in changing to a more egalitarian approach to job titles including at the ministerial and chief executive level. You will see our approach explained on page 16 of our style guide. We have argued for the removal of the ‘deferential’ rule, and a clear explanation of how to handle job titles and professions. We suggest that more detail should be included in your content, with clear examples that are not ambiguous.
 
En dashes vs Em dashes – we definitely support the argument proposed by NSW Department of Education and I’m curious about why Gov.AU recommends an em dash. As a group none of us could recall seeing an em dash in recent history, because en dashes are the norm. On page 14 of our style guide we give a lot of detail, including replacing the word ‘to’ for spans of time. Microsoft Word also creates an automatic en dash in most circumstances where one is required, and so from our perspective asking staff to try to remember a key command or do anything special would not be successful. In our view, an em dash also looks overly long and quite old fashioned.
 
Latin abbreviations – we support limiting the use of eg, ie and etc but we believe that eg is now so common that it is unlikely to be a CALD issue. Our approach is to limit the use of these abbreviations but to use them where appropriate. We changed from using a comma after these abbreviations to adopting the Gov.UK approach of no punctuation at all.
 
Quotation marks – we have been using double quotes for speech and single quotes to demarcate a word or phrase, or for quotes within a quote. We understand that many agencies and publishers prefer to use single quotes as the standard for everything, and so we will recommend – based on the Gov.AU approach – that we update our style to use single quotes.
 
Passive/active voice and government tone – we really appreciated this section and plan to link to your content in our next iteration of the DECD writing style guide. In our experience the more examples of plain English the better as often people can’t see passive, bureaucratic language until it is pointed out to them via examples.
 
Adjectival phrases vs possessive – although your guide does not cover this (as yet), there is one example you use (drivers licence) which is commonly regarded as an adjectival rather than possessive phrase, along with travellers cheques and workers compensation. Page 8 of our style guide goes into detail about apostrophes and mentions this, which is pretty standard. We suggest that you correct the example so as not to confuse people about this topic, and perhaps add a section about adjectival phrases that do not need an apostrophe, especially as there is uncertainty and disagreement about where an apostrophe would be placed.
 
Numbers and measurements – our big departure from traditional style conventions was to choose the digital best practice convention over print eg using numerals in all instances except when starting a sentence or in a phrase such as one-to-one or one-off. Our guide on page 15 goes into more detail. Our main feedback on Gov.AU is in the detail of writing times: we believe that these should consistently be 4 digit rather than sometimes 2 digit and sometimes 4 in your examples. This would mean 10.00am and not 10am and any time segments come within this rule – 10.15am, 9.45am etc.
 
Financial years – after researching how the ATO and other financially based organisations handle financial years, we opted for the hyphen rather than the oblique eg 2016-17 rather than 2016/17. Though the issue of screen readers did come up, we felt that the standard convention should apply rather than the word ‘to’. We would be interested to hear your views on this.
 
We really appreciated your content about literacy levels in Australia and writing for a 10-12-year-old reader. This is useful for us to mention in training our staff about the importance of Plain English.
 
Our writing style guide is currently under review for its annual update. I would welcome any feedback about our writing style guide, and look forward to joining in dialogue with DTA and Gov.AU.
 
Warm regards
 
 
Anne-marie Taplin
Senior Writer, Communications directorate
Department for Education and Child Development | 31 Flinders Street, Adelaide SA 5000
t (08) 8226 0942  e Anne-marie.Taplin@sa.gov.au w www.decd.sa.gov.au 
Facebook | Twitter | LinkedIn

**Comment by joolswood** [comment]
Need to go through and extract relevant things.

**Comment by gazanson** [comment]
Now being tracked in Trello
