### ISSUE TITLE
SEO guidance

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#173]
Relates to https://waffle.io/govau/content-guide/cards/58e5bebb38f230003ebfb1e5

**Comment by joolswood** [comment]
https://waffle.io/govau/content-guide/cards/58e5bebb38f230003ebfb1db also relates

**Comment by libbyv** [comment]
Steve Hibbins to supply final version for uploading as a new section. Please also review Guide for related content and add hyperlinks where appropriate.

**Comment by libbyv** [comment]
https://docs.google.com/a/digital.gov.au/document/d/1utX6Fx5uhb3mWGCDdqgFj1SKWbippP6ur5-WneAsVAQ/edit?usp=sharing

**Comment by joolswood** [comment]
Hi @gazanson maybe keep this open until it's live on production?

**Comment by joolswood** [comment]
Re-opening to remind us to change the URLs from the SEO section to Guides test URL to production URLs when both things go live. @gazanson

**Comment by joolswood** [comment]
Tracking in Trello
