### ISSUE TITLE
Acronyms - eg WoG, WOG etc

### ISSUE THREAD

**Issue by libbyv** [govau/content-guide#174]
Do we need to include guidance around lowercase/uppercase usage in acronyms as per Google Group discussion.

**Comment by joolswood** [comment]
Look at Michael's email in Google Group.

**Comment by gazanson** [comment]
#174 [guidance around lowercase/uppercase usage in acronyms as per Google Group discussion. (eg WoG, WOG)] — a rule that says that all letters of an acronymed organisation or other reference are either ALL capitalised, or whether a blend of capitals and lowercase are used, depending on the grammatical role of each word in the acronym.] 
-------------------------
Discuss this proposed guidance (Gary A draft)...

Acronyms

Organisational acronyms

The first time you use an abbreviation or an acronym for an organisation, spell it out in full unless it’s well known, like ‘ABC’ or ‘RSPCA’.  ‘Well known’ means that 80% of Australians will understand and use it. 

In general:
1. use the most common acronym for the organisation — ordinarily the one it uses itself; if that isn’t known ...
2. capitalise all words excluding conjunctions (‘and’), prepositions (‘of’) and definite and indefinite articles (‘a’ and ‘the’).

Exceptions

WoG   -  Whole-of-Government

**Comment by joolswood** [comment]
Didn't we talk about trying to lead people away from using `Whole of Government`? (as it is typically used in an inaccurate way)

**Comment by gazanson** [comment]
Yes -- we have the option of supporting and recommending 'WoAG' -- as per Finance use: https://www.finance.gov.au/procurement/travel-and-related-services/

**Comment by gazanson** [comment]
Now being tracked in Trello
