### ISSUE TITLE
Referencing

### ISSUE THREAD

**Issue by libbyv** [govau/content-guide#175]
We need to create some guidance around how to do online referencing.

**Comment by libbyv** [comment]
We haven’t got to this yet in Content Guide so for now I’d guess it would be a decision based on a combination of:
- the quantity of references (is it useful for the user to see dozens of full references within the page, or does that get in the way of more useful content?)
- consistency across the publication (is there a house style that applies here?)

**Comment by libbyv** [comment]
Some things we might include when talking about referencing: 

Linking to the source if you can (using wording that accurately describes the destination of the link)
Considering the usability of the page - for example, will lots of references disrupt the user experience of reading and understanding the information
Consistent heading structure
Minimising italics (hard to read on a screen and difficult for people with dyslexia)
If there is a user need to create the content as a PDF, make sure it is accessible
Making sure the PDF is printable if it's a print doc

**Comment by joolswood** [comment]
Tracking in Trello
