### ISSUE TITLE
There is no SC 1.1.5

### ISSUE THREAD

**Issue by awkawk** [govau/content-guide#178]
You mean 1.4.5

## What do you need?

What is the problem?

## Which entry/section is this related to?

For example: Hyperlinks

## Good example

Have you seen content guidance elsewhere we should look at?

**Comment by joolswood** [comment]
Thanks awkawk. @gazanson this relates to the `Images of text`-`WCAG criteria 1.1.5 (Level AA)`in /accessibility-inclusivity/

**Comment by joolswood** [comment]
Thanks @awkawk - just merged a change to fix this.
