### ISSUE TITLE
Google page title length in Content Guide

### ISSUE THREAD

**Issue by SteveDTA** [govau/content-guide#179]
Current guidance on Google page titles says 55 characters. The wording also refers to 'Google searches'. Does this mean the title tag? I was a little unsure. If so, the character length for Google is now 70 for Google.

**Comment by libbyv** [comment]
Review new guidance from Steve/Ilan to make sure we are crossing our i's etc re SEO application to the Content Guide URL

**Comment by gazanson** [comment]
Now being tracked in Trello
