### ISSUE TITLE
Same sex inclusivity language

### ISSUE THREAD

**Issue by libbyv** [govau/content-guide#181]
Add guidance around same sex to inclusivity guidance as per email: Good afternoon,
 
I am wondering if the content in your online style guide is relevant to all APS departments and agencies. Our comms area is currently reviewing our Department’s style guide–which has an inclusive language section. The DIBP Diversity and Inclusion Team has provided feedback on this part of the guide and feel that some diversity cohorts, that the APS as a whole supports, are missing relevant content. For example gender and sexual orientation in particular.
 
I have been advised that our style guide is based on the DTA online style guide, so I was wondering in your diversity and inclusion section is to be updated to align to the language that is being used throughout the APS, and in line with the Secretaries Equality and Diversity Council.
 
Appreciate your advice.
 
Cheers
Elissa
 
Elissa Byfield
 
Diversity and Inclusion Team | Performance, Career and Inclusion Section
People Strategy and Policy Branch | People Division
Corporate Group
Department of Immigration and Border Protection
P: 02 6223 9008
E: elissa.byfield@border.gov.au
E: diversity@border.gov.au

**Comment by libbyv** [comment]
See also http://consciousstyleguide.com/gender-sex-sexuality/

**Comment by gazanson** [comment]
Now being tracked in Trello
