### ISSUE TITLE
Add F shaped pattern info

### ISSUE THREAD

**Issue by libbyv** [govau/content-guide#183]
https://www.nngroup.com/videos/f-pattern-reading-digital-content/?utm_source=Alertbox&utm_campaign=c9691900e0-Service_Blueprints_Back-to-Top_2017_08_28&utm_medium=email&utm_term=0_7f29a2b335-c9691900e0-24409913

**Comment by joolswood** [comment]
Keep in icebox; maybe come back later if we need to say something specifically on this.

**Comment by gazanson** [comment]
Now being tracked in Trello
