### ISSUE TITLE
H2s render as links

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#2]
Remove hover and underline from H2s in pages.
![screen shot 2017-02-14 at 1 11 08 pm](https://cloud.githubusercontent.com/assets/13774080/22912030/106502f0-f2b7-11e6-8734-67fd34152639.png)
![screen shot 2017-02-14 at 1 10 23 pm](https://cloud.githubusercontent.com/assets/13774080/22911991/f5307b90-f2b6-11e6-9be0-92492253b679.png)

**Comment by klepas** [comment]
Done — uncommented line 460 in `guide.scss`: https://github.com/govau/content-guide/commit/d05197bb8ac7c5e239033bb3500b21f42e68424d

**Comment by klepas** [comment]
Doh. I see what the haps are — will fix.

**Comment by klepas** [comment]
Fixed. Just needed to remove the class from the homepage: https://github.com/govau/content-guide/commit/3231cf22ee14219c5af1fa81b517de0b84727afa
