### ISSUE TITLE
Correct highly-intelligent example

### ISSUE THREAD

**Issue by libbyv** [govau/content-guide#200]
From Lisa H

I just noticed in the style guide the following example is not the best.  ‘Intelligent’ is an adjective not a noun.

 

https://guides.service.gov.au/content-guide/punctuation-grammar/

 

Do not use hyphens when joining an adverb to a noun.

Example of

not using hyphens to join adverb to noun

highly intelligent — not highly-intelligent

**Comment by gazanson** [comment]
Now being tracked in Trello
