### ISSUE TITLE
Review bullet point guidance

### ISSUE THREAD

**Issue by libbyv** [govau/content-guide#201]
Hi,
 
Just having a conversation with a colleague and we were quite confused about the difference in capitalisations/full stops for bulleted lists (https://guides.service.gov.au/content-guide/content-structure/#bullet-point-lists).
 
I’m not sure what governed the decision around sentence fragments vs full sentences but wouldn’t it be easier if all bulleted lists followed the same style. Eg. All start with caps, last bullet ends with a full stop.
 
If not, some more examples might be useful, especially in relation to more complex lists where there’s some ambiguity as to if the bulleted list is a sentence fragment or not.
 
Thanks,
Danushka
 
Danushka Silva
Digital Content Advisor
Digital Casey (ViBE)
City of Casey
 
PO Box 1000, Narre Warren VIC 3805
T. 03 9792 7291
E. dsilva@casey.vic.gov.au
W. www.casey.vic.gov.au

**Comment by libbyv** [comment]
Gary to see if we can add some more examples to help make our guidance clearer.

**Comment by gazanson** [comment]
Now being tracked in Trello
