### ISSUE TITLE
Single vs. double quotation marks

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#218]
Can we discuss moving to recommending double quotation marks over single.

There are a number of reasons this is smart:
- easier to distinguish from apostrophe when scanning
- single quotation marks ignored by ChromeVox
- is 18F and GOV.UK approach

**Comment by gazanson** [comment]
Noni to user test ... approach? testing readability
Liz to check w Krista to test at end of each session
Test waters with Google group -- case  for and against (Meaghan)
Include definitive advice on accessibility 
Then tread water till style manual?

**Comment by libbyv** [comment]
See ticket 117 - related

**Comment by gazanson** [comment]
Now being tracked in Trello
