### ISSUE TITLE
Remove www from links

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#22]
## What do you need?

https://github.com/AusDTO/gov-au-content-guide/issues/162

## Which entry/section is this related to?

https://github.com/govau/content-guide/blame/develop/_content-structure/hyperlinks.md

**Comment by joolswood** [comment]
I've omitted guidance on referencing www from the site --- until we can agree on the best wording.

**Comment by gazanson** [comment]
Now being tracked in Trello
