### ISSUE TITLE
Extra guidance on bullet points

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#23]
## What do you need?

- See @fearlesssteven changes https://github.com/AusDTO/gov-au-content-guide/pull/211/commits/faa2294f326f8da6956074053267d5db5c5477de - - 
- https://github.com/AusDTO/gov-au-content-guide/issues/121
- https://github.com/AusDTO/gov-au-content-guide/pull/211
- https://github.com/AusDTO/gov-au-content-guide/pull/202/files
- https://github.com/AusDTO/gov-au-content-guide/issues/180

## Which entry/section is this related to?

https://github.com/govau/content-guide/blob/develop/_content-structure/bullet-point-lists.md

**Comment by joolswood** [comment]
Michael will do some examples for the clinic to review.

**Comment by gazanson** [comment]
Now being tracked in Trello
