### ISSUE TITLE
Gerunds guidance

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#24]
## What do you need?

Continuing the epic gerund discussion begun at https://github.com/AusDTO/gov-au-content-guide/issues/106 & https://github.com/AusDTO/gov-au-content-guide/pull/192

## Which entry/section is this related to?

http://content-guide.apps.staging.digital.gov.au/writing-style/index.html#voice (probably not the right place!)

**Comment by gazanson** [comment]
Guidance on gender and sexuality terms
