### ISSUE TITLE
DIBP feedback

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#25]
## What do you need?

Reviewing [suggestions for Content Guide entries received from DIBP](https://docs.google.com/a/digital.gov.au/document/d/1e61Mgh16KnUHSBusb0AWb9iz84rrBVYnMm63ZD6CMvE/edit?usp=sharing). In particular the capitalisation of proper nouns (Department and Minister etc) - would like to resolve this before we publish the new guide.

Reference: [DIBP Writing style guide](https://drive.google.com/a/digital.gov.au/file/d/0B476d7OhSs9gZnpRQlJjU0NEYk0/view?usp=sharing)

https://github.com/AusDTO/gov-au-content-guide/issues/221

**Comment by joolswood** [comment]
- Content Clinic: agree with uppercase D and M
- But need to provide some minimal guidance about user not understanding department.
- Expand Department example to add '... we'

**Comment by joolswood** [comment]
This commit https://github.com/govau/content-guide/commit/dc434608f937317bd70e3954c9284165b267eedc should achieve Content Clinic request.

**Comment by gazanson** [comment]
Now being tracked in Trello
