### ISSUE TITLE
Alpha or alpha / Beta or beta

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#27]
## What do you need?

Alpha or alpha / Beta or beta - seems like this is inconsistently applied across DTA materials

## Which entry/section is this related to?

http://content-guide.apps.staging.digital.gov.au/terms-phrases/#preferred-spellings

https://github.com/AusDTO/gov-au-content-guide/issues/222

**Comment by gazanson** [comment]
Now being tracked in Trello
