### ISSUE TITLE
Focused vs focussed

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#28]
## What do you need?

Focused or focussed? Have noticed both about the place. Prefer focused myself.

## Which entry/section is this related to?

http://content-guide.apps.staging.digital.gov.au/terms-phrases/#preferred-spellings

**Comment by AndrewArch** [comment]
hey - what did the Macquarie say?

**Comment by joolswood** [comment]
We've added guidance that follows the Macquarie: http://content-guide.apps.staging.digital.gov.au/terms-phrases/#preferred-spellings
