### ISSUE TITLE
Referring to all 3 levels of government together

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#29]
## What do you need?

https://github.com/AusDTO/gov-au-content-guide/issues/190

## Which entry/section is this related to?

http://content-guide.apps.staging.digital.gov.au/terms-phrases/index.html#australian-government
http://content-guide.apps.staging.digital.gov.au/terms-phrases/#states-territories

**Comment by joolswood** [comment]
Revisit as part of a content pattern

**Comment by joolswood** [comment]
Add: `Australian Government, state and territory, and local government`.

**Comment by gazanson** [comment]
Now being tracked in Trello
