### ISSUE TITLE
Implement search

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#4]
~2~ acceptable short-term solutions (depending on time available):
1. ~Implement Google search box.~
2. Implement luna.js search (DTA.gov.au search).

**Comment by bjgordon** [comment]
@joolswood I've implemented the lunr.js search, and search extracts are now shown. It will show the first 40 words of the page, but you can override by adding "searchextract" front matter to the page. For the case of your collections index pages this is in `_pages/collections`
Next I will add the search to the front page now.

**Comment by joolswood** [comment]
@bjgordon thanks. I don't suppose there's an easy way to preserve line breaks in the 40 word snippets?

**Comment by joolswood** [comment]
As discussed @bjgordon please can we remove the snippets for now. Cheers.

**Comment by bjgordon** [comment]
I think just one thing left to fix - the searchbar placeholder text in the header so it works < IE 9

**Comment by joolswood** [comment]
Also see #90

**Comment by klepas** [comment]
Related also: #92.
