### ISSUE TITLE
Time zones

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#40]
## What do you need?

https://github.com/AusDTO/gov-au-content-guide/issues/193
https://github.com/AusDTO/gov-au-content-guide/issues/178
https://github.com/AusDTO/gov-au-content-guide/issues/174

## Which entry/section is this related to?

http://content-guide.apps.staging.digital.gov.au/numbers-measurements/#hours-minutes

**Comment by gazanson** [comment]
Now being tracked in Trello
