### ISSUE TITLE
Addressing/referring to a user

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#43]
## What do you need?

https://github.com/AusDTO/gov-au-content-guide/issues/127

## Which entry/section is this related to?

http://content-guide.apps.staging.digital.gov.au/writing-style/#tone

**Comment by joolswood** [comment]
Hey @meaghan-n I think we were discussing this the other day?

**Comment by meaghan-n** [comment]
Partly...I think this question relates more to forms of address?

**Comment by gazanson** [comment]
Now being tracked in Trello
