### ISSUE TITLE
Glossary!

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#45]
## What do you need?

https://github.com/AusDTO/gov-au-content-guide/issues/153
https://github.com/AusDTO/gov-au-content-guide/issues/179

## Which entry/section is this related to?

http://content-guide.apps.staging.digital.gov.au/terms-phrases/

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/45

**Comment by joolswood** [comment]
Bumping this forward - we have user need to get some specific terms in guidance soon, if not all of them.

**Comment by joolswood** [comment]
Relevant stuff here @libbyv https://sites.google.com/a/digital.gov.au/dtointranet/home/how-do-i-1/understand-dto-words

**Comment by libbyv** [comment]
Here is a round-up of all glossaries that need to be combined into 1: https://docs.google.com/document/d/18p2_kGSnwdpOqax8WDz2uUa7Fl3dPwR--wKFjXyFrNU/edit

**Comment by gazanson** [comment]
Now being tracked in Trello
