### ISSUE TITLE
Specify external links

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#5]
Add `rel="external"` to all external links.

**Comment by joolswood** [comment]
I'd be grateful for your help @klepas to come up with an automated way of doing this.

**Comment by joolswood** [comment]
Can I get some help with this @bjgordon to see if there's a quicker way of doing this - and checking broken links.

**Comment by bjgordon** [comment]
@joolswood We could do it with javascript, but it should also be possible for a jekyll plugin to do it which would be preferred. I found a [newish jekyll plugin](https://github.com/d-ogarkov/jekyll-extlinks) which might work, I'll assign this issue to me and give it a go.

**Comment by joolswood** [comment]
Hey @bjgordon I've finished it semi-manually https://github.com/govau/content-guide/pull/83 but maybe that plugin you spotted can automate future ones?

Any thoughts on how we can do a broken link check?

**Comment by bjgordon** [comment]
@joolswood I can add an internal link checker on every site build. For external links, it's better for that to be a scheduled task rather than being part of the site build, so I'll do that separately.

**Comment by joolswood** [comment]
Hey @bjgordon how are you going with the link checking? Do we need a new issue for this?

**Comment by bjgordon** [comment]
Oh I'd forgotten about that. Maybe create a new issue and assign it to me

**Comment by joolswood** [comment]
Will do, thanks @bjgordon

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/89
