### ISSUE TITLE
'Skip to' links guidance

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#52]
## What do you need?

https://github.com/AusDTO/gov-au-content-guide/issues/141

**Comment by joolswood** [comment]
Add brief mention

**Comment by gazanson** [comment]
See change and comment - https://docs.google.com/document/d/1mnkOQCR-FhziM3-bWFRYJogjjzUBVGgzCbZu9YBT4cA/edit?disco=AAAABT36yzI

**Comment by joolswood** [comment]
Tracked in Trello now
