### ISSUE TITLE
Provide guidance on writing headings to be contextually meaningful when read stand-alone

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#54]
## What do you need?

https://github.com/AusDTO/gov-au-content-guide/issues/146

## Which entry/section is this related to?

http://content-guide.apps.staging.digital.gov.au/content-structure/#headings-subheadings

**Comment by gazanson** [comment]
Consider adding to the UI KIT and/or Content Patterns? Feedback received was: “Confusing to screen reader “Get more help” 5 x a page is crap; “Get more help with X” is useful.”

**Comment by gazanson** [comment]
Now being tracked in Trello
