### ISSUE TITLE
Ordering of collection items in home page columns

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#6]
Correct the ordering of items to go from top to bottom, not left to right.
![screen shot 2017-02-14 at 1 20 40 pm](https://cloud.githubusercontent.com/assets/13774080/22912261/651d4630-f2b8-11e6-991d-c978a8ebe1b1.png)

**Comment by joolswood** [comment]
Blocked? by #11

**Comment by klepas** [comment]
No longer an issue due to the design changes made in #11.
