### ISSUE TITLE
Content types

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#62]
## What do you need?

https://github.com/AusDTO/gov-au-content-guide/issues/154

## Which entry/section is this related to?

http://content-guide.apps.staging.digital.gov.au/content-types/

**Comment by joolswood** [comment]
We need to re-scope / re-prioritise this task as we now have a types of content page in our content guide.

**Comment by libbyv** [comment]
Content types are being addressed in content strategy. New ticket to be opened re restructuring current Content Types to be Content Types (annual reports etc) and Content Formats (Word etc)
