### ISSUE TITLE
Blockquote rendering

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#8]
2 issues:
1. rendering of double quotation marks is potentially confusing for other users to implement and goes against our punctuation guidance. Suggest we remove them entirely.
2. the change of font is jarring (also harder to read than default font). Suggest changing to body font.

![screen shot 2017-02-14 at 1 24 07 pm](https://cloud.githubusercontent.com/assets/13774080/22912333/f7c8ac36-f2b8-11e6-80c7-2365ddbfabd7.png)

Perhaps we can use similar insert text style as GDS?

![screen shot 2017-02-14 at 1 26 02 pm](https://cloud.githubusercontent.com/assets/13774080/22912357/252c315c-f2b9-11e6-849b-60ff5f836286.png)

**Comment by joolswood** [comment]
Let's pair up on this as discussed @klepas

**Comment by klepas** [comment]
Fixed in https://github.com/AusDTO/gov-au-ui-kit/pull/479

@joolswood / @gazhands did you still want me to change this back to the default (sans serif) font?

**Comment by klepas** [comment]
I set them to sans serif (in uikit, and then updated the submodule again.
