### ISSUE TITLE
Graphic for header

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#9]
We should use something different from the DTA Design Guide graphic to help users understand they are at a different guide.
![Uploading Screen Shot 2017-02-14 at 2.59.12 pm.png…]()

**Comment by gazhands** [comment]
![content guide - home](https://cloud.githubusercontent.com/assets/17328069/23593135/0757e8dc-025f-11e7-8986-8ff5b4bd016f.png)

**Comment by gazhands** [comment]
[content-header.svg.zip](https://github.com/govau/content-guide/files/819915/content-header.svg.zip)

**Comment by gazhands** [comment]
[content-guide-icon.svg.zip](https://github.com/govau/content-guide/files/819920/content-guide-icon.svg.zip)

**Comment by joolswood** [comment]
@klepas pls use this branch https://github.com/govau/content-guide/tree/feature/11-home-template

**Comment by klepas** [comment]
Missing mbl design. I worked it to make the header graphic appear between the logo and the hero lead in text just like in the Design Guide.

Not sure how to cater for the recently added search box — created #92 for that.
