### ISSUE TITLE
Improve search page

### ISSUE THREAD

**Issue by joolswood** [govau/content-guide#90]
## What do you need?

Make search page more useful by:
- [ ] removing excess white space
- [ ] removing borders under search results
- [ ] I'd suggest removing the inline search box from the search results page - it's still available in the header (see the 18F version below)
- [ ] turn results into plain text list?

## Which entry/section is this related to?

Search result page

## Good example

https://pages.18f.gov/content-guide/search/?q=links
![screen shot 2017-03-07 at 2 01 26 pm](https://cloud.githubusercontent.com/assets/13774080/23639955/9563eb8c-033e-11e7-8df6-401a567dffd6.png)

**Comment by klepas** [comment]
I didn’t get around to this today, and the few lines I started on this last night are junk. Soz.
