### ISSUE TITLE
Fix search box placement in mbl & tablet viewports

### ISSUE THREAD

**Issue by klepas** [govau/content-guide#92]
## What do you need?

Let the search box be usable in mbl & tablet viewports.

What is the problem?

The search box overlaps with other header/hero content.

## Which entry/section is this related to?

All pages — homepage header as well as inner page header.

**Comment by joolswood** [comment]
There's also a bug with `Search` text overlapping a search query when you tab out of the box:
![screen shot 2017-03-17 at 9 42 48 am](https://cloud.githubusercontent.com/assets/13774080/24021664/18db483e-0af6-11e7-944f-9d6936109fc4.png)
