### ISSUE TITLE
Add GA to Guides

### ISSUE THREAD

**Issue by joahua** [govau/content-guide#94]

**Comment by joolswood** [comment]
Blocked by #73

**Comment by joolswood** [comment]
Now also blocked by temporarily not having Google Analytics access.

**Comment by bjgordon** [comment]
It might be worth just creating a temp account for GA before you go live, [you can migrate it](https://support.google.com/analytics/answer/6370521?hl=en) later.

**Comment by joolswood** [comment]
Hey good idea @bjgordon Just running this by Toby.
